name: Python Lint
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  python-lint:
    uses: ministryofjustice/data-engineering-github-actions/.github/workflows/reusable-python-lint.yml@main
